redis:
  main:
    host: localhost
    port: 6379

jwt:
  secret: ${JWT_SECRET}
  expiration: 3600000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/zariyo
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
